[package]
name = "linear-shared"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
embedded-hal.workspace = true

[features]

esp32 = []

esp32c3 = []
