[package]
name = "linear-shared"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
esp-hal = { workspace = true }

[features]

esp32c3 = ["esp-hal/esp32c3"]

esp32 = ["esp-hal/esp32"]
